---
kind: Service
apiVersion: v1
metadata:
  name: get-service
  labels:
    app: get
spec:
  selector:
    app: get
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
...
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: get-deployment
spec:
  selector:
    matchLabels:
      app: get
  replicas: 1
  template:
    metadata:
      labels:
        app: get
    spec:
      containers:
      - name: get
        image: ghostgoose33/get-python:v2
        ports:
        - containerPort: 5000
        env:
        - name: URL_DB
          valueFrom:
            configMapKeyRef:
              name: services-address
              key: URL_DB
...