apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: get-deployment
spec:
  selector:
    matchLabels:
      app: get
  replicas: 1
  template:
    metadata:
      labels:
        app: get
    spec:
      containers:
      - name: get
        image: ghostgoose33/get-python:v2
        ports:
        - containerPort: 5000
